FailedToCreateGame = "Failed to create game"
FailedToUpdateGame = "Failed to update game"
GameNotFound = "Game not found"
InvalidGameState = "Invalid game state"
InvalidCountParameter = "Invalid count parameter"
FailedToRetrieveGames = "Failed to retrieve games"
