name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: v1.16.1
      - name: build
        run: go build
